### ISSUE TITLE
Error In find_text_similarity()

### ISSUE THREAD

**Issue by hmontero1205** [saintnate/pwp-capstones#1]
You made a typo in this function that caused the final similarity scores to be incorrect.
Your return statement was this: ` return (word_count_similarity + word_count_similarity + ngram_similarity) / 3`

You probably meant to write this: ` return (sentence_length_similarity + word_count_similarity + ngram_similarity) / 3`

**Comment by saintnate** [comment]
Revisions/corrections made in Version 3 files
