### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by hmontero1205** [saintnate/pwp-capstones#2]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 3.5

### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 3.5

### Criteria 3: Software Architecture
* _Score Level:_ 3.5
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4

### Overall Score: 14.5/16

You almost caught the murderer! Because of a small typo you made, the similarity scores were wrong :(. If it weren't for that though, you would've caught him. Be sure to check your code before submitting next time to catch these small errors.

**Comment by saintnate** [comment]
@hmontero1205 thank you so much for the constructive and in-depth feedback!
