### ISSUE TITLE
Average Sentence Length Code

### ISSUE THREAD

**Issue by hmontero1205** [saintnate/pwp-capstones#3]
I am not sure if this was intentional, but the code you wrote to get the average sentence length is really weird. It works, but I am not convinced you know why it works.
```
for sentence in sentence_list:
        word_list = []
        word_list.append(sentence.split())
        for word in word_list:
            for i in word:
                word_count += len(word_list)
```

When you do `word_list.append(sentence.split())`, you aren't adding each word to `word_list`, you're actually adding a list to `word_list`.
If I had `I am Hans` as a sentence, your code would create `[ ['I', 'am', 'Hans'] ]` and assign it to `word_list`. As you can see, there is only one item in `word_list`, a list.
`word` gets assigned to the list `['I', 'am', 'Hans'] ` and `i` gets assigned to each word.
You then add ` len(word_list)` for each word.. As I explained before, ` len(word_list)` is 1.

Luckily, this code works, but it is poorly designed. Here are two versions.
First, there is no need for `word_list`, and the inner loop.
```
for sentence in sentence_list:
        for word in sentence.split()
                word_count += 1
```

From here, just use the `len()` function.
```
for sentence in sentence_list:
       word_count += len(sentence.split(" "))
```

**Comment by saintnate** [comment]
Revisions/corrections made in Version 3 files
