### ISSUE TITLE
General Code Style

### ISSUE THREAD

**Issue by hmontero1205** [saintnate/pwp-capstones#6]
Please be mindful of your code style -- it matters too.
Sometimes you do `a = a + b` but sometimes you do `a += b`.
Sometimes you do `a = b + c` but sometimes you do `a=b+c`.
Be neat and be consistent!

I also want to say that you should only name for loop variables `i` if you're dealing with numbers. It's a widely accepted practice. If it's not a number, give the variable an actual descriptive name. Save single letters for things like numbers (i) or characters (c).

**Comment by saintnate** [comment]
Revisions/corrections made in Version 3 files
